gpt_oss_120b_local:
  prompt_template: "chatgpt/basic_prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "openai/gpt-oss-120b"
    max_new_tokens: 64
    temperature: 0.0
    do_sample: false
  completion_parser_kwargs:
    outputs_to_match:
      1: "(?:^|\\n) ?Output \\(a\\)"
      2: "(?:^|\\n) ?Output \\(b\\)"
  batch_size: 1
